version: '3'

services:
  coinkeeper-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://docker:docker@coinkeeper-db:5432/apicoinkeeper?schema=public
      - JWT_SECRET=secret
    depends_on:
      - coinkeeper-db
    volumes:
      - .:/app
      - /app/node_modules
  coinkeeper-db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apicoinkeeper
    volumes:
      - coinkeeper-db:/bitnami/postgresql
volumes:
  coinkeeper-db:
    driver: local